<?php
/**
 * TODO: Description
 *
 * @category    
 * @package     
 * @author      Rolando Espinoza La fuente (rho@prosoftpeople.com)
 * @copyright   Copyright (c) 2008-2009 Pro Soft Resources USA Inc. (http://www.prosoftpeople.com)
 * @license     $License$
 * @version     $Id$
 */
?>
<h1>Test</h1>

<?php if (count($this->messages) > 0): ?>
    <div class="messages">
        <ul>
        <?php foreach ($this->messages as $message): ?>
            <li><?= $this->escape($message) ?></li> 
        <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

<?= $this->form ?>

<div id="ajax-result">
</div>
