<?php
/**
 * TODO: Description
 *
 * @category    
 * @package     
 * @author      Rolando Espinoza La fuente (rho@prosoftpeople.com)
 * @copyright   Copyright (c) 2008-2009 Pro Soft Resources USA Inc. (http://www.prosoftpeople.com)
 * @license     $License$
 * @version     $Id$
 */
?>
<html>
<head>
<title>Test</title>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
<script type="text/javascript" src="<?= $this->baseUrl() ?>/scripts/site.js?<?= time() ?>"></script>
</head>
<body>
<?= $this->layout()->content ?>
</body>
</html>
